### ISSUE TITLE
почему influx? 

### ISSUE THREAD

**Issue by tomarcafe** [cyberFund/kenig.cyber.fund#1]
какие есть альтернативы, и почему из них именно инфлюкс выбран?

**Comment by tomarcafe** [comment]
http://blog.outlyer.com/top10-open-source-time-series-databases

**Comment by 21xhipster** [comment]
Я думаю что использование инфлюкса или ему подобных не имеет смысла для калькуляций балансов по счетам, индексации транзакций, за исключением вопросов измерения цены (ордер бук)

**Comment by litvintech** [comment]
Инфлюкса не будет, остановились на orbit-db + RethinkDB(маркет + аккаунты) + ElasticSearch (для полнотекстового поиска по блокчейнам)
